import { ForbiddenException, Injectable } from '@nestjs/common';

import { PermissionFlagType } from 'twenty-shared/constants';
import { isDefined } from 'twenty-shared/utils';

import { ALL_ERP_PROTECTED_METADATA_OBJECT_NAMES } from 'src/engine/core-modules/erp/constants/erp-protected-metadata-object-names.constant';
import { WorkspaceManyOrAllFlatEntityMapsCacheService } from 'src/engine/metadata-modules/flat-entity/services/workspace-many-or-all-flat-entity-maps-cache.service';
import { PermissionsService } from 'src/engine/metadata-modules/permissions/permissions.service';

const REGISTER_REFUSAL_MESSAGE = (objectNameSingular: string) =>
  `Регистр «${objectNameSingular}» формируется автоматически при проведении документов — добавление полей и вьюх запрещено.`;

const MUTATION_REFUSAL_MESSAGE =
  'AI-кастомизация метаданных (MVP) поддерживает только создание новых объектов, полей и вьюх. ' +
  'Изменение и удаление существующих объектов и полей через AI пока не поддерживается — используйте Settings UI.';

const ADMIN_REQUIRED_MESSAGE =
  'Недостаточно прав: изменение модели данных (объекты, поля, вьюхи) требует права администратора workspace (DATA_MODEL).';

// Tool names generated by ObjectMetadataToolsFactory/FieldMetadataToolsFactory
// (core-modules/tool-provider/providers/metadata-tool.provider.ts) and
// ViewToolsFactory (.../view-tool.provider.ts) that mutate existing metadata.
// MVP ruling (Phase 8 T2): only creation is allowed through AI customization;
// update/delete of both custom and app-owned objects/fields is refused
// unconditionally, so no app-ownership resolution is needed for these — the
// outcome does not depend on who owns the target. Upgrade path: once the
// product needs "let an agent rename its own custom field", split this set by
// applicationId (see ErpCustomizationSurfaceService, which already resolves
// custom vs app-owned for the read side).
const BLOCKED_MUTATION_TOOL_NAMES = new Set([
  'update_object_metadata',
  'update_many_object_metadata',
  'delete_object_metadata',
  'update_field_metadata',
  'update_many_field_metadata',
  'delete_field_metadata',
]);

// Tool names that create new object/field metadata. New objects/fields are
// always created under workspaceCustomFlatApplication by the underlying
// services (ObjectMetadataService.createOneObject / FieldMetadataService.
// createOneField, see object-metadata.service.ts:459-467) unless the caller
// passes ownerFlatApplication — which none of these MCP-reachable tools do —
// so app-ownership is never in question for creation; only the register
// check applies.
const CREATE_OBJECT_TOOL_NAMES = new Set([
  'create_object_metadata',
  'create_many_object_metadata',
]);

const CREATE_FIELD_TOOL_NAMES = new Set([
  'create_field_metadata',
  'create_many_field_metadata',
]);

type ToolCallArgs = Record<string, unknown>;

const asRecord = (value: unknown): ToolCallArgs | undefined =>
  isDefined(value) && typeof value === 'object' && !Array.isArray(value)
    ? (value as ToolCallArgs)
    : undefined;

const asArray = (value: unknown): unknown[] =>
  Array.isArray(value) ? value : [];

// Guards the generic create_object_metadata/create_field_metadata/create_view
// family (already MCP-exposed via execute_tool through MetadataToolProvider/
// ViewToolProvider) with the Phase 8 "фронтир AI-кастомизации" ruling: the 4
// ERP registers are off-limits, only creation is allowed (not update/delete),
// and the whole frontier requires workspace-admin-level permission
// (PermissionFlagType.DATA_MODEL — the same flag object-metadata.resolver.ts/
// field-metadata.resolver.ts gate Settings UI's object/field creation with).
// This is the schema-permission counterpart to ErpObjectPermissionGuardService
// (record-level); that pair doesn't fit here because it checks
// rolesPermissions[roleId][objectId], not a workspace setting flag.
@Injectable()
export class ErpMetadataToolGuardService {
  constructor(
    private readonly permissionsService: PermissionsService,
    private readonly flatEntityMapsCacheService: WorkspaceManyOrAllFlatEntityMapsCacheService,
  ) {}

  // toolName is the METADATA/VIEW category tool name (e.g.
  // "create_field_metadata"), not the top-level MCP tool name — call from
  // MetadataToolProvider.executeStaticTool / ViewToolProvider.executeStaticTool,
  // which is where execute_tool ultimately dispatches both categories for
  // MCP and any future in-app AI chat caller (same ToolExecutorService path).
  async assertToolCallAllowed({
    toolName,
    args,
    workspaceId,
    roleId,
  }: {
    toolName: string;
    args: ToolCallArgs;
    workspaceId: string;
    roleId: string;
  }): Promise<void> {
    if (BLOCKED_MUTATION_TOOL_NAMES.has(toolName)) {
      throw new ForbiddenException(MUTATION_REFUSAL_MESSAGE);
    }

    const isCreateView =
      toolName === 'create_view' ||
      (toolName === 'upsert_complete_view' && !isDefined(args.id));

    const isCreateField = CREATE_FIELD_TOOL_NAMES.has(toolName);
    const isCreateObject = CREATE_OBJECT_TOOL_NAMES.has(toolName);
    const isCreateRelation = toolName === 'create_many_relation_fields';

    if (
      !isCreateObject &&
      !isCreateField &&
      !isCreateRelation &&
      !isCreateView
    ) {
      // Read tools (get_object_metadata, get_views, ...) and out-of-scope
      // view tools (update_view, delete_view, upsert_complete_view in update
      // mode) keep their existing permission model (VIEWS flag) — views are
      // display config, not schema, and admin-gating personal view edits
      // would regress legitimate non-admin AI-assisted view usage that the
      // plan's frontier never intended to restrict.
      return;
    }

    await this.assertIsWorkspaceAdmin({ workspaceId, roleId });

    if (isCreateObject) {
      // A brand-new object can never collide with an existing register name
      // in a way that matters here (the platform's own uniqueness validation
      // rejects a duplicate nameSingular) — nothing further to check.
      return;
    }

    if (isCreateField) {
      const objectMetadataIds = this.extractCreateFieldObjectMetadataIds(
        toolName,
        args,
      );

      await this.assertObjectsNotProtected({ workspaceId, objectMetadataIds });

      return;
    }

    if (isCreateRelation) {
      const objectMetadataIds =
        this.extractCreateRelationObjectMetadataIds(args);

      await this.assertObjectsNotProtected({ workspaceId, objectMetadataIds });

      return;
    }

    // isCreateView
    const objectNameSingular = this.extractCreateViewObjectName(toolName, args);

    if (isDefined(objectNameSingular)) {
      this.assertObjectNameNotProtected(objectNameSingular);
    }
  }

  private async assertIsWorkspaceAdmin({
    workspaceId,
    roleId,
  }: {
    workspaceId: string;
    roleId: string;
  }): Promise<void> {
    const hasDataModelPermission =
      await this.permissionsService.checkRolesPermissions(
        { unionOf: [roleId] },
        workspaceId,
        PermissionFlagType.DATA_MODEL,
      );

    if (!hasDataModelPermission) {
      throw new ForbiddenException(ADMIN_REQUIRED_MESSAGE);
    }
  }

  private extractCreateFieldObjectMetadataIds(
    toolName: string,
    args: ToolCallArgs,
  ): string[] {
    if (toolName === 'create_field_metadata') {
      const objectMetadataId = args.objectMetadataId;

      return typeof objectMetadataId === 'string' ? [objectMetadataId] : [];
    }

    // create_many_field_metadata: { fields: [{ objectMetadataId, ... }] }
    return asArray(args.fields)
      .map((field) => asRecord(field)?.objectMetadataId)
      .filter((id): id is string => typeof id === 'string');
  }

  private extractCreateRelationObjectMetadataIds(args: ToolCallArgs): string[] {
    // create_many_relation_fields: { relations: [{ objectMetadataId,
    // targetObjectMetadataId, ... }] } — a relation field also writes an
    // inverse field onto the target object, so both ends must clear the
    // register check, not just the source.
    return asArray(args.relations).flatMap((relation) => {
      const record = asRecord(relation);

      return [record?.objectMetadataId, record?.targetObjectMetadataId].filter(
        (id): id is string => typeof id === 'string',
      );
    });
  }

  private extractCreateViewObjectName(
    toolName: string,
    args: ToolCallArgs,
  ): string | undefined {
    if (toolName === 'create_view' || toolName === 'upsert_complete_view') {
      const objectNameSingular = args.objectNameSingular;

      return typeof objectNameSingular === 'string'
        ? objectNameSingular
        : undefined;
    }

    return undefined;
  }

  private assertObjectNameNotProtected(objectNameSingular: string): void {
    if (ALL_ERP_PROTECTED_METADATA_OBJECT_NAMES.includes(objectNameSingular)) {
      throw new ForbiddenException(
        REGISTER_REFUSAL_MESSAGE(objectNameSingular),
      );
    }
  }

  private async assertObjectsNotProtected({
    workspaceId,
    objectMetadataIds,
  }: {
    workspaceId: string;
    objectMetadataIds: string[];
  }): Promise<void> {
    if (objectMetadataIds.length === 0) {
      return;
    }

    const { flatObjectMetadataMaps } =
      await this.flatEntityMapsCacheService.getOrRecomputeManyOrAllFlatEntityMaps(
        {
          workspaceId,
          flatMapsKeys: ['flatObjectMetadataMaps'],
        },
      );

    for (const objectMetadataId of new Set(objectMetadataIds)) {
      const universalIdentifier =
        flatObjectMetadataMaps.universalIdentifierById[objectMetadataId];
      const objectMetadata = isDefined(universalIdentifier)
        ? flatObjectMetadataMaps.byUniversalIdentifier[universalIdentifier]
        : undefined;

      if (isDefined(objectMetadata)) {
        this.assertObjectNameNotProtected(objectMetadata.nameSingular);
      }
    }
  }
}
